on:
  push:
    branches: master

name: pkgdown-win

jobs:
  pkgdown:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "pkgdown"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_local(".")
        shell: Rscript {0}

      - name: Deploy package
        run: pkgdown::deploy_to_branch(new_process = FALSE, branch = "gh-pages-win")
        shell: Rscript {0}
